// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpeedAlert.Infrastructure.Persistence;

#nullable disable

namespace SpeedAlert.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422181636_HardenProviderAndTrackingModels")]
    partial class HardenProviderAndTrackingModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpeedAlert.Domain.Entities.AlertEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ActualSpeedKph")
                        .HasColumnType("double precision");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DrivingSessionId")
                        .HasColumnType("uuid");

                    b.Property<double>("SpeedLimitKph")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DrivingSessionId");

                    b.ToTable("AlertEvents");
                });

            modelBuilder.Entity("SpeedAlert.Domain.Entities.DeviceStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BackgroundLocationGranted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBatteryOptimized")
                        .HasColumnType("boolean");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("DeviceStatuses");
                });

            modelBuilder.Entity("SpeedAlert.Domain.Entities.DrivingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AlertEventCount")
                        .HasColumnType("integer");

                    b.Property<double>("AverageSpeedKph")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MaxSpeedKph")
                        .HasColumnType("double precision");

                    b.Property<double>("MostSevereOverspeedKph")
                        .HasColumnType("double precision");

                    b.Property<int>("OverspeedEventCount")
                        .HasColumnType("integer");

                    b.Property<string>("SessionEndReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionStartReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("TotalDistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasAutoStarted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Active'");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("SpeedAlert.Domain.Entities.ProviderConfig", b =>
                {
                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastFailureAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastFailureReason")
                        .HasColumnType("text");

                    b.Property<string>("LastHealthStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PriorityOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProviderKey");

                    b.ToTable("ProviderConfigs");
                });

            modelBuilder.Entity("SpeedAlert.Domain.Entities.RoadLookupCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FallbackUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("LookupStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderUsedKey")
                        .HasColumnType("text");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoadName")
                        .HasColumnType("text");

                    b.Property<string>("SegmentIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("SelectedProviderKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("SpeedLimitKph")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CacheKey", "SelectedProviderKey")
                        .IsUnique();

                    b.ToTable("RoadLookupCaches");
                });

            modelBuilder.Entity("SpeedAlert.Domain.Entities.SessionPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AccuracyMeters")
                        .HasColumnType("double precision");

                    b.Property<Guid>("DrivingSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double>("SpeedKph")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DrivingSessionId", "Timestamp");

                    b.ToTable("SessionPoints");
                });

            modelBuilder.Entity("SpeedAlert.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SpeedAlert.Domain.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("AlertCooldownSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("AlertDelaySeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("AutoDetectDrivingEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoStartMonitoringEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("OverspeedTolerance")
                        .HasColumnType("integer");

                    b.Property<bool>("SoundEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("SpeedUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("VibrationEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("VoiceEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("SpeedAlert.Domain.Entities.AlertEvent", b =>
                {
                    b.HasOne("SpeedAlert.Domain.Entities.DrivingSession", "DrivingSession")
                        .WithMany("Alerts")
                        .HasForeignKey("DrivingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrivingSession");
                });

            modelBuilder.Entity("SpeedAlert.Domain.Entities.DrivingSession", b =>
                {
                    b.HasOne("SpeedAlert.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpeedAlert.Domain.Entities.SessionPoint", b =>
                {
                    b.HasOne("SpeedAlert.Domain.Entities.DrivingSession", "DrivingSession")
                        .WithMany("Points")
                        .HasForeignKey("DrivingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrivingSession");
                });

            modelBuilder.Entity("SpeedAlert.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("SpeedAlert.Domain.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("SpeedAlert.Domain.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpeedAlert.Domain.Entities.DrivingSession", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Points");
                });

            modelBuilder.Entity("SpeedAlert.Domain.Entities.User", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("Settings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
